name: 'Setup'
description: 'Full CI env setup (setup node & restore/install dependencies)'

runs:
    using: composite
    steps:
        -   name: "Setup node env"
            uses: actions/setup-node@v3
            with:
                registry-url: 'https://registry.npmjs.org'
                node-version-file: '.nvmrc'

        -   name: "Cache dependencies"
            id: cache
            uses: actions/cache@v4
            with:
                path: |
                  **/node_modules
                  .yarn/cache
                key: ${{ runner.os }}-node-v${{ inputs.node_version }}-dependency-hash-${{ hashFiles('yarn.lock') }}
                restore-keys: |
                    ${{ runner.os }}-node-v${{ inputs.node_version }}-dependency-hash-

        -   name: "Install dependencies"
            run: yarn install
            shell: bash


