name: 'Setup'
description: 'Full CI env setup (setup node & restore/install dependencies)'

inputs:
    node_version:
        description: 'Node version to use'
        default: '16.10.0'

runs:
    using: composite
    steps:
        -   name: "Setup node env"
            uses: actions/setup-node@v3
            with:
                node-version: ${{ inputs.node_version }}
                registry-url: 'https://registry.npmjs.org'

        -   name: "Cache dependencies"
            id: cache
            uses: actions/cache@v3
            with:
                path: "**/node_modules"
                key: ${{ runner.os }}-dependency-hash-${{ hashFiles('yarn.lock') }}2
                restore-keys: |
                    ${{ runner.os }}-dependency-hash-

        -   name: "Install dependencies"
            # Skip install here because the cache already has an entry, we won't be able to update it, so it's unnecessary to try and rebuild it
            if: steps.cache.outputs.cache-hit != 'true'
            run: yarn install
            shell: bash


