nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.0.cjs

logFilters:
    # Hide peer dependency resolution warnings
    - level: 'discard'
      code: 'YN0002'
    # Hide architecture is incompatible warnings
    - level: 'discard'
      code: 'YN0076'
