export {
    DIALOG_TRANSITION_DURATION,
    IS_BROWSER,
    WINDOW,
    DOCUMENT,
    NOTIFICATION_TRANSITION_DURATION,
    TOOLTIP_HOVER_DELAY,
    TOOLTIP_LONG_PRESS_DELAY,
    VISUALLY_HIDDEN,
} from '@lumx/core/js/constants';
