name: 'Increment package versions'
description: 'Increment all package.json versions and update CHANGELOG'

inputs:
    releaseType:
        description: 'Release type'
        required: true
        default: 'prerelease'
        type: choice
        options:
            - prerelease
            - patch
            - minor
            - major
    prereleaseName:
        description: 'Prerelease name (ignore if release type is not `prerelease`)'
        default: 'alpha'
        type: string
outputs:
    distTag:
        description: "NPM dist tag (latest, alpha, etc.)"
        value: ${{ fromJSON(steps.version.outputs.result).distTag }}
    prevDistTagVersion:
        description: "Previous version in the dist tag (if any)"
        value: ${{ fromJSON(steps.version.outputs.result).prevDistTagVersion }}
    nextVersion:
        description: "Next version"
        value: ${{ fromJSON(steps.version.outputs.result).nextVersion }}
    releaseBranch:
        description: "Name of the release branch"
        value: ${{ fromJSON(steps.version.outputs.result).releaseBranch }}

# Example release:
#   - name: Upgrade package versions
#     uses: ./.github/actions/increment-package-versions
#     with:
#         releaseType: 'patch'


# Example prerelease:
#   - name: Upgrade package versions
#     uses: ./.github/actions/increment-package-versions
#     with:
#         releaseType: 'prerelease'
#         prereleaseName: 'beta'

runs:
    using: composite
    steps:
        -   name: Upgrade package versions
            id: version
            uses: actions/github-script@v6
            with:
                script: |
                    return require("${{ github.action_path }}")({
                        github, context, inputs: ${{ toJSON(inputs) }}
                    })
