#!/bin/bash
. "$(dirname $0)/_/husky.sh"

NAME="commit-message-validator"
VERSION="1.0.0"
DOWNLOAD="https://github.com/lumapps/$NAME/archive/refs/tags/$VERSION.zip"
REPO_DIR="$(dirname $0)/_/$NAME"
VERSION_DIR="${REPO_DIR}/${VERSION}"

# Get or update git repository
(
    set -x
    if [[ ! -d "$VERSION_DIR" ]]; then
        rm -rf "$REPO_DIR"
        mkdir -p "$VERSION_DIR"
        cd "$VERSION_DIR"
        # Download from github (-L => follow HTTP redirections)
        curl "$DOWNLOAD" -L --output "$VERSION.zip"
        # Unzip
        unzip "$VERSION.zip"
        # Move all files in current dir
        mv "${NAME}-${VERSION}"/* .
    fi
) > /dev/null 2>&1

# Run commit validator (--no-jira remove the JIRA ticket requirement)
cat | "$VERSION_DIR/check_message.sh" "--no-jira" "$@"
