name: Chromatic

on:
  pull_request:
    types: [ opened, synchronize, reopened, labeled ]
  push:
    tags:
        - v*

env:
    node_version: '13.7.0'

jobs:
  deploy:
    # Run on push version tag OR on PR with the "need: review-design" label
    if: "github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'need: review-design')"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f #v2.3.4
        with:
            fetch-depth: 0 # retrieve all the repo history (required by chromatic)

      - name: "Setup node env"
        uses: actions/setup-node@c6fd00ceb9747fb23ffdf72987450a2664414867 #v2.1.2
        with:
            node-version: ${{ env.node_version }}

      - name: "Install dependencies"
        run: yarn install --immutable

      - name: "Deploy chromatic"
        uses: chromaui/action@3f82bf5d065290658af8add6dce946809ee0f923 #v6.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          buildScriptName: build:storybook
