name: Chromatic

on:
    pull_request:
        types: [ opened, synchronize, reopened, labeled ]
    push:
        tags:
            - v*
            - '!v*-alpha.*' # ignore alpha versions

concurrency:
    group: chromatic-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    deploy:
        # Run on push version tag OR on PR with the "need: deploy-chromatic" label
        if: "github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'need: deploy-chromatic')"
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0 # retrieve all the repo history (required by chromatic)

            -   name: "Setup"
                uses: ./.github/actions/setup

            -   name: "Deploy chromatic"
                uses: chromaui/action@3f82bf5d065290658af8add6dce946809ee0f923 #v6.1.0
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    projectToken: ${{ secrets.CHROMATIC_TOKEN }}
                    buildScriptName: build:storybook

            -   if: "contains(github.event.pull_request.labels.*.name, 'need: deploy-chromatic')"
                name: "Remove label"
                uses: ./.github/actions/remove-label
                with:
                    label: "need: deploy-chromatic"
