name: Chromatic

on:
    pull_request:
        types: [ opened, synchronize, reopened, labeled ]
    push:
        tags:
            - v*
            - '!v*-alpha.*' # ignore alpha versions

env:
    node_version: '13.7.0'

jobs:
    dependencies:
        name: "dependencies"
        # Run on push version tag OR on PR with the "need: deploy-chromatic" label
        if: "github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'need: deploy-chromatic')"
        uses: ./.github/workflows/dependencies.yml

    deploy:
        # Run on push version tag OR on PR with the "need: deploy-chromatic" label
        if: "github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'need: deploy-chromatic')"
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0 # retrieve all the repo history (required by chromatic)

            -   name: "Setup node env"
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ env.node_version }}

            -   name: "Restore dependency cache"
                id: cache
                uses: actions/cache@v3
                with:
                    path: "**/node_modules"
                    key: ${{ needs.dependencies.outputs.cacheKey }}

            -   name: "Install dependencies"
                if: steps.cache.outputs.cache-hit != 'true'
                run: yarn install

            -   name: "Deploy chromatic"
                uses: chromaui/action@3f82bf5d065290658af8add6dce946809ee0f923 #v6.1.0
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    projectToken: ${{ secrets.CHROMATIC_TOKEN }}
                    buildScriptName: build:storybook

            -   if: "contains(github.event.pull_request.labels.*.name, 'need: deploy-chromatic')"
                name: "Remove label"
                uses: ./dev-packages/ga-remove-label
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    LABEL: "need: deploy-chromatic"

