name: "Deploy chromatic release"

# Chromatic deploy on release cannot run in `release.yml` until this is merged: https://github.com/chromaui/chromatic-cli/pull/695
# Triggering on tag push might not work since GitHub workflows cascade are disabled by default.

on:
    push:
        tags:
            - v*
            - '!v*-alpha.*' # ignore alpha versions

concurrency:
    group: chromatic-release-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
    deploy_chromatic:
        name: "Deploy chromatic"
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0 # retrieve all the repo history (required by chromatic)

            -   name: "Setup"
                uses: ./.github/actions/setup

            -   name: "Deploy chromatic"
                uses: chromaui/action@3f82bf5d065290658af8add6dce946809ee0f923 #v6.1.0
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    projectToken: ${{ secrets.CHROMATIC_TOKEN }}
                    buildScriptName: build:storybook
