name: "Publish Release Workflow"

# When merging release commit on master
# - Build & publish NPM libs
# - Create & push git tag
# - Build & publish demo site docker image
# - Deploy chromatic
# - Create GH release notes

on:
    push:
        branches:
            - master

concurrency:
    group: "${{ github.workflow }}-${{ github.ref_name }}"
    cancel-in-progress: true

jobs:
    is_release_commit:
        name: "Check is release commit"
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v3

            -   name: "Check is release commit"
                id: check
                env:
                    GH_TOKEN: ${{ github.token }}
                uses: actions/github-script@v6
                with:
                    script: |
                        const run = require('util').promisify(require('child_process').exec);
                        const commitMessage = await run(`git show -s --format=%s`)
                            .then(({ stdout }) => stdout.trim());
                        const isReleaseCommit = commitMessage?.matches(/chore\(release\): release.*/)

                        const { version } = require('./lerna.json');
                        return { version, isReleaseCommit };
        outputs:
            is_release_commit: ${{ fromJSON(steps.check.outputs.result).isReleaseCommit }}
            version: ${{ fromJSON(steps.check.outputs.result).version }}

    build_publish_NPM:
        name: "Build & publish NPM libs"
        needs: [is_release_commit]
        if: ${{ needs.is_release_commit.outputs.is_release_commit }}
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v3

            -   name: "Setup"
                uses: ./.github/actions/setup

            -   name: "Build libs"
                run: yarn build:libs

            -   name: "Publish version to NPM"
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                run: |
                    for package in $(echo packages/lumx-*);
                    do
                        (echo "Publishing $package"; cd $package/dist; npm publish --tag latest)
                    done

    git_tag:
        name: "Create & push git tag"
        needs: [ is_release_commit, build_publish_NPM ]
        if: ${{ needs.is_release_commit.outputs.is_release_commit }}
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: "Git commit, tag & push"
                id: git
                run: |
                    git config --global user.name "github-actions"
                    git config --global user.email "github-actions@users.noreply.github.com"

                    tag="v${{ needs.is_release_commit.outputs.version }}"
                    echo "tag=$tag" >> $GITHUB_OUTPUT

                    # Tag and push tag
                    git tag "$tag"
                    git push origin "$tag"
        outputs:
            tag: ${{ steps.git.outputs.tag }}

    deploy_chromatic:
        name: "Deploy chromatic"
        needs: [is_release_commit, build_publish_NPM]
        if: ${{ needs.is_release_commit.outputs.is_release_commit }}
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0 # retrieve all the repo history (required by chromatic)

            -   name: "Setup"
                uses: ./.github/actions/setup

            -   name: "Deploy chromatic"
                uses: chromaui/action@3f82bf5d065290658af8add6dce946809ee0f923 #v6.1.0
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    projectToken: ${{ secrets.CHROMATIC_TOKEN }}
                    buildScriptName: build:storybook

    build_demo_site:
        name: "Build & push demo site"
        needs: [is_release_commit]
        if: ${{ needs.is_release_commit.outputs.is_release_commit }}
        timeout-minutes: 30
        runs-on: ubuntu-latest
        env:
            GCP_PROD_REGISTRY: gcr.io/lumapps-registry
        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v3

            -   name: "Login to GCR"
                uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
                with:
                    registry: gcr.io
                    username: _json_key
                    password: ${{ secrets.GCR_PROD_RW_CREDS }}

            -   name: "Setup buildx"
                id: buildx_setup
                uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325
                with:
                    install: true

            -   run: |
                    echo "git_commit=$(git rev-parse HEAD)" >> $GITHUB_ENV
                    echo "build_date=$(date --rfc-3339=seconds)" >> $GITHUB_ENV

            -   name: "Docker metadata"
                id: meta
                uses: docker/metadata-action@f206c36955d3cc6213c38fb3747d9ba4113e686a
                with:
                    tags: |
                        type=match,pattern=/^v?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
                        type=raw,enable=true,priority=200,value=${{ env.git_commit }},event=tag
                    images: |
                        ${{ env.GCP_PROD_REGISTRY }}/design-system
                    labels: |
                        com.lumapps.image.created=${{ env.build_date }}
                        com.lumapps.image.sha1=${{ env.git_commit }}
                        com.lumapps.image.authors=frontend@lumapps.com
                        com.lumapps.image.version={{tag}}

            -   name: "Build image"
                uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
                with:
                    context: ./
                    file: ${{ matrix.dockerfile }}
                    builder: ${{ steps.buildx_setup.outputs.name }}
                    build-args: version=${{ env.version }}
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    cache-from: type=gha, scope=${{ github.workflow }}
                    cache-to: type=gha, scope=${{ github.workflow }}, mode=max

    create_gh_release:
        name: "Create release note"
        needs: [is_release_commit, git_tag]
        if: ${{ needs.is_release_commit.outputs.is_release_commit }}
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v3

            -   name: "Create release note"
                uses: ./.github/actions/release-note
                with:
                    versionTag: ${{ needs.git_tag.outputs.tag }}


