name: "Create GitHub Release Notes"

# Generate a release note when a new release tag is pushed on GitHub

on:
    push:
        tags:
            - v*
            - '!v*-alpha.*' # ignore alpha versions

concurrency:
    group: "${{ github.workflow }}-${{ github.ref_name }}"
    cancel-in-progress: true

jobs:
    create_gh_release:
        name: "Create release note"
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v3

            -   name: "Create release note"
                uses: ./.github/actions/release-note
                with:
                    versionTag: ${{ github.ref_name }}

